# Generated by Django 4.0.6 on 2022-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('photos', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['title', 'created_at'],
            },
        ),
    ]
