# Generated by Django 4.0.6 on 2022-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='добавлено'),
        ),
        migrations.AlterField(
            model_name='greenery',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='greenery',
            name='photos',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='greenery',
            name='title',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
    ]
